// <auto-generated />
namespace VidlyTutorial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedCreateAndUpdateForMoviesAndCustomers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedCreateAndUpdateForMoviesAndCustomers));
        
        string IMigrationMetadata.Id
        {
            get { return "202103211750179_AddedCreateAndUpdateForMoviesAndCustomers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
